/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sasken_demo_Hello */

#ifndef _Included_com_sasken_demo_Hello
#define _Included_com_sasken_demo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sasken_demo_Hello
 * Method:    func1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sasken_demo_Hello_func1
  (JNIEnv *, jobject);

/*
 * Class:     com_sasken_demo_Hello
 * Method:    func2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sasken_demo_Hello_func2
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
